// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using ApplicazioniReali.Db.Models;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using ApplicazioniReali.API.ModelsIdentity;

#nullable disable

namespace ApplicazioniReali.Db.Data
{
    public partial class IdentityContext : IdentityDbContext<AppUser>
    {
        public IdentityContext()
        {
        }

        public IdentityContext(DbContextOptions<IdentityContext> options)
            : base(options)
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Data Source=ALE-ASUS-PROART;Initial Catalog=ApplicazioniReali;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
        }
    }
}