// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ApplicazioniReali.Db.Models
{
    public partial class User
    {
        public Guid Id { get; set; }
        public string AspNetUsersId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime Dob { get; set; }

        public virtual AspNetUser AspNetUsers { get; set; }
    }
}